[2023-05-11T04:55:54.005+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Mongodb_backup.scp_to_server manual__2023-05-11T04:53:48.861953+00:00 [queued]>
[2023-05-11T04:55:54.015+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Mongodb_backup.scp_to_server manual__2023-05-11T04:53:48.861953+00:00 [queued]>
[2023-05-11T04:55:54.016+0000] {taskinstance.py:1331} INFO - Starting attempt 2 of 3
[2023-05-11T04:55:54.030+0000] {taskinstance.py:1350} INFO - Executing <Task(BashOperator): scp_to_server> on 2023-05-11 04:53:48.861953+00:00
[2023-05-11T04:55:54.037+0000] {standard_task_runner.py:57} INFO - Started process 1473 to run task
[2023-05-11T04:55:54.043+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Mongodb_backup', 'scp_to_server', 'manual__2023-05-11T04:53:48.861953+00:00', '--job-id', '115', '--raw', '--subdir', 'DAGS_FOLDER/dagforbackup.py', '--cfg-path', '/tmp/tmpbg56wky5']
[2023-05-11T04:55:54.044+0000] {standard_task_runner.py:85} INFO - Job 115: Subtask scp_to_server
[2023-05-11T04:55:54.125+0000] {task_command.py:410} INFO - Running <TaskInstance: Mongodb_backup.scp_to_server manual__2023-05-11T04:53:48.861953+00:00 [running]> on host b06a232a05e5
[2023-05-11T04:55:54.227+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Mongodb_backup' AIRFLOW_CTX_TASK_ID='scp_to_server' AIRFLOW_CTX_EXECUTION_DATE='2023-05-11T04:53:48.861953+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-11T04:53:48.861953+00:00'
[2023-05-11T04:55:54.229+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-05-11T04:55:54.230+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', ' \nscp -i ~/Downloads/3-mar-2023-N.Virginia.pem /Users/archanakarpe/Documents/saraff/MongoConnectionDags/dags/dbbackup.sh ubuntu@107.23.137.161:/home/ubuntu']
[2023-05-11T04:55:54.248+0000] {subprocess.py:86} INFO - Output:
[2023-05-11T04:55:54.264+0000] {subprocess.py:93} INFO - Warning: Identity file /home/***/Downloads/3-mar-2023-N.Virginia.pem not accessible: No such file or directory.
[2023-05-11T04:55:55.385+0000] {subprocess.py:93} INFO - Host key verification failed.
[2023-05-11T04:55:55.387+0000] {subprocess.py:93} INFO - lost connection
[2023-05-11T04:55:55.390+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-05-11T04:55:55.436+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-05-11T04:55:55.444+0000] {taskinstance.py:1373} INFO - Marking task as UP_FOR_RETRY. dag_id=Mongodb_backup, task_id=scp_to_server, execution_date=20230511T045348, start_date=20230511T045554, end_date=20230511T045555
[2023-05-11T04:55:55.464+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 115 for task scp_to_server (Bash command failed. The command returned a non-zero exit code 1.; 1473)
[2023-05-11T04:55:55.520+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-11T04:55:55.552+0000] {dagrun.py:701} ERROR - Failed to get task for ti <TaskInstance: Mongodb_backup.test_ssh_operator manual__2023-05-11T04:53:48.861953+00:00 [None]>. Marking it as removed.
[2023-05-11T04:55:55.564+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
